allow the site url to be configurable
IoIxD/DFS pull request #65
Opened 2022-10-16 01:07 UTC by IoIxD

#### I have made sure all the things still work:

- [x] The index page and privacy policy page is still served
- [x] The sitemap isn't broken.
- [x] The guild listing ((example))[http://localhost:8084/592399417676529688] is still functioning
- [x] A guild's message listing ((example))[http://localhost:8084/592399417676529688/1015021717900513363] is still functioning.
- The following post pages are still functioning:
    - [x] [Why the Slash Commands? Why aren't my images working?](http://localhost:8084/592399417676529688/1015021717900513363/1015031189779796099) (very complete page that showcases most of the features)
    -  [ ] [Post your oshi!.. THE FORUM](http://localhost:8084/662191386942111744/1019811690042368060/1023640405067177984) (the largest page that we serve at over 4,448 messages)
    - [x] [Any but not all of the posts in the test forum](https://dfs.ioi-xd.net/1020045037372964974/1020049276082073630)

2022-10-17 15:24 UTC, samhza requested changes
CI is failing and there are still references to `dfs.ioi-xd.net` that should be removed:
https://github.com/IoIxD/DFS/blob/6631794e18adc875b2399d833fc94f355bef3a6a/resources/templates/guild.gohtml#L6
https://github.com/IoIxD/DFS/blob/6631794e18adc875b2399d833fc94f355bef3a6a/resources/templates/post.gohtml#L33
https://github.com/IoIxD/DFS/blob/6631794e18adc875b2399d833fc94f355bef3a6a/resources/templates/forum.gohtml#L7
https://github.com/IoIxD/DFS/blob/6631794e18adc875b2399d833fc94f355bef3a6a/resources/templates/index.gohtml#L13

2022-10-17 15:24 UTC, samhza commented on main.go
> +var siteURL string
This should be a field in the server type, not a global

2022-10-21 05:59 UTC, samhza submitted a review, later dismissed

2022-10-21 06:18 UTC, IoIxD commented
reviewed on another site

2022-10-21 06:18 UTC, merged